#!/usr/bin/env python3
"""caf -- Calculation framework.

Usage:
    caf build [new]
    caf work

Commands:

Options:
"""
from docopt import docopt
from caflib.Core import Context
import imp
import os
from datetime import datetime


def load_cscript():
    cscript = imp.new_module('cscript')
    try:
        exec(compile(open('cscript').read(), 'cscript', 'exec'), cscript.__dict__)
    except:
        import traceback
        import sys
        print('There was an error while reading cscript.')
        traceback.print_exc()
        sys.exit(1)
    return cscript


if __name__ == '__main__':
    args = docopt(__doc__)
    if args['build']:
        cscript = load_cscript()
        ctx = Context()
        cscript.build(ctx)
        if args['new']:
            blddir = format(datetime.today(), '%Y-%m-%d_%H:%M:%S')
            os.system('mkdir -p build/{}'.format(blddir))
            os.system('ln -fns {} build/latest'.format(blddir))
        ctx.build()
