#!/usr/bin/env python3
import subprocess as sp


from caflib.Scheduler import Scheduler
from caflib.Utils import cd


scheduler = Scheduler('.caf')
for task in scheduler.tasks():
    with cd(task.path):
        with open('run.out', 'w') as stdout, open('run.err', 'w') as stderr:
            try:
                sp.check_call(task.command, shell=True, stdout=stdout, stderr=stderr)
            except sp.CalledProcessError as exc:
                task.error(exc)
            else:
                task.done()
