#!/usr/bin/env python3
from caflib.Configure import Context
from caflib.Cellar import Cellar


import cscript
cellar = Cellar('.caf')
ctx = Context('.', cellar)
cscript.configure(ctx)
ctx.sort_tasks()
ctx.process()
conf = ctx.get_configuration()
# import json
# print(json.dumps(conf, indent=4, sort_keys=True))
