#!/usr/bin/env python3
from caflib.Configure import Context
import json


import cscript
ctx = Context('.')
cscript.configure(ctx)
ctx.process()
conf = ctx.get_configuration()
print(json.dumps(conf, indent=4, sort_keys=True))
