#!/usr/bin/env python3


def _compile(task):
    from pathlib import Path
    src = task.consume('src')
    task.attrs['command'] = 'gcc -o {0} {1}'.format(Path(src).stem, src)


def compress(task):
    task.attrs['command'] = 'tar -zchf {0}.tar.gz {0}'.format(task.consume('file'))


def build(ctx):
    [ctx(features=_compile,
         src='hello.c',
         templates='hello.c',
         name=name) +
     ctx.target('build', name) +
     ctx.link('build', 'hello') +
     ctx(features=compress,
         file='hello') +
     ctx.target('package', name) +
     ctx.link(name)
     for name in ['Alice', 'Bob', 'Eve']] +\
        ctx(command='for f in */hello.tar.gz; do tar -xf $f && ./hello && mv hello hello_`dirname $f`; done') +\
        ctx.target('run')
