#!/usr/bin/env python3


def prepare_sum(task):
    with open('a.in', 'w') as f:
        print(task.consume('a'), file=f)
    with open('b.in', 'w') as f:
        print(task.consume('b'), file=f)
    task.attrs['command'] = 'expr `cat a.in` + `cat b.in`'


def prepare_square(task):
    x = int(open('data.txt').read())
    with open('x.in', 'w') as f:
        print(x, file=f)


def build(ctx):
    [[ctx(features=prepare_sum, a=a, b=b+i) +
      ctx.link(name, ('run.out', name + '.in'))
      for i, name in [(1, 'x'), (2, 'y')]] +
     ctx(command='expr `cat x.in` \* `cat y.in` >data.txt') +
     ctx.target('data', (a, b)) +
     ctx.link('data', 'data.txt', needed=True) +
     ctx(features=prepare_square, files='square.sh', command='./square.sh') +
     ctx.target('results', (a, b)) +
     ctx.link((a, b))
     for a in range(0, 5) for b in range(0, a)] + \
        ctx(command='cat */run.out | python -c "import sys; print(sum(map(int, sys.stdin)))"') + \
        ctx.target('analysis')
