#!/usr/bin/env python
from caflib.Core import Calculation

top = '..'


class ExampleCalculation(Calculation):
    def __init__(self, **kwargs):
        super(self.__class__, self).__init__('a.in', 'b.in', **kwargs)
        self.command = 'expr `cat a.in` + `cat b.in`'


def prepare(ctx):
    for n in range(5):
        ctx.add_task(ExampleCalculation(n=n), n=n)


def extract(ctx):
    return int(open('run.out').read())


def process(ctx):
    with open('results.txt', 'w') as f:
        f.write('{}\n'.format({r.param['n']: r.data for r in ctx.results}))
